name: flash_chat_flutter
description: A new Flutter project based on the current version.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.2
  firebase_core: ^1.24.0
  firebase_core_web: ^1.7.3
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  modal_progress_hud: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
